services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data-zee:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_HOST: '%'
    networks:
      -  my-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-padmin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  flaskapp:
    image: zeeshankanuga/flask-app:latest
    container_name: flask-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: mydb

    command: >
      sh -c "sleep 30 && python app.py"

    networks:
      - my-network

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      mysql:
        condition: service_healthy


networks:
  my-network:
    driver: bridge

volumes:
  mysql-data-zee: {}
